#include<windows.h>

#ifndef WM_USER
#define WM_USER 0x0400
#endif


#define WM_IMAGE WM_USER + 1
#define WM_ADD_FACE WM_USER + 2
#define WM_ADD_PERSON WM_USER +3
#define WM_GET_RECOGNITION_ID WM_USER + 4
#define WM_GET_SERVER_ID WM_USER + 5
#define WM_EXIT WM_USER + 6
#define WM_RESULT WM_USER + 7
#define WM_RESULT_DECTIVE WM_USER + 8
#define WM_RESULT_FIND WM_USER + 9
#define WM_RECOGNITION_ERROR WM_USER + 10
#define WM_CLIENT_DISCONNECT WM_USER + 11
#define WM_MODIFY WM_USER + 12
#define WM_ADD_FACE_FAILED WM_USER + 13
#define WM_ADD WM_USER + 15
#define WM_RECOGNIZE WM_USER + 16
#define WM_SAVE WM_USER + 17
#define WM_SERVER_ID WM_USER + 19